# coding: utf-8

# flake8: noqa

"""
    Chat API SDK

    The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sale@chat-api.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api._instance_api import InstanceApi
from openapi_client.api._messages_api import 2MessagesApi
from openapi_client.api.3_chats_api import 3ChatsApi
from openapi_client.api.4_webhooks_api import 4WebhooksApi
from openapi_client.api.5_queues_api import 5QueuesApi
from openapi_client.api.6_ban_api import 6BanApi
from openapi_client.api.7_testing_api import 7TestingApi

# import ApiClient
from openapi_client.api_client import ApiClient

# import Configuration
from openapi_client.configuration import Configuration

# import exceptions
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.ack import Ack
from openapi_client.models.ban_settings import BanSettings
from openapi_client.models.ban_test_action import BanTestAction
from openapi_client.models.ban_test_status import BanTestStatus
from openapi_client.models.chat import Chat
from openapi_client.models.chat_id_prop import ChatIdProp
from openapi_client.models.chat_update import ChatUpdate
from openapi_client.models.chats import Chats
from openapi_client.models.clear_actions_queue_status import ClearActionsQueueStatus
from openapi_client.models.clear_messages_queue_status import ClearMessagesQueueStatus
from openapi_client.models.create_group_action import CreateGroupAction
from openapi_client.models.create_group_status import CreateGroupStatus
from openapi_client.models.forward_message_request import ForwardMessageRequest
from openapi_client.models.group_participant_action import GroupParticipantAction
from openapi_client.models.group_participant_status import GroupParticipantStatus
from openapi_client.models.inline_response200 import InlineResponse200
from openapi_client.models.inline_response2001 import InlineResponse2001
from openapi_client.models.inline_response2002 import InlineResponse2002
from openapi_client.models.inline_response2003 import InlineResponse2003
from openapi_client.models.inline_response2004 import InlineResponse2004
from openapi_client.models.inline_response2005 import InlineResponse2005
from openapi_client.models.inline_response2005_update import InlineResponse2005Update
from openapi_client.models.inline_response401 import InlineResponse401
from openapi_client.models.instance_status import InstanceStatus
from openapi_client.models.instance_status_action import InstanceStatusAction
from openapi_client.models.instance_status_link import InstanceStatusLink
from openapi_client.models.instance_status_status_data import InstanceStatusStatusData
from openapi_client.models.instance_status_status_data_actions import InstanceStatusStatusDataActions
from openapi_client.models.message import Message
from openapi_client.models.messages import Messages
from openapi_client.models.outbound_action import OutboundAction
from openapi_client.models.outbound_actions import OutboundActions
from openapi_client.models.outbound_message import OutboundMessage
from openapi_client.models.outbound_messages import OutboundMessages
from openapi_client.models.phone_prop import PhoneProp
from openapi_client.models.read_chat_action import ReadChatAction
from openapi_client.models.read_chat_status import ReadChatStatus
from openapi_client.models.send_contact_request import SendContactRequest
from openapi_client.models.send_file_request import SendFileRequest
from openapi_client.models.send_link_request import SendLinkRequest
from openapi_client.models.send_location_request import SendLocationRequest
from openapi_client.models.send_message_request import SendMessageRequest
from openapi_client.models.send_message_status import SendMessageStatus
from openapi_client.models.send_ptt_request import SendPTTRequest
from openapi_client.models.send_v_card_request import SendVCardRequest
from openapi_client.models.set_webhook_status import SetWebhookStatus
from openapi_client.models.settings import Settings
from openapi_client.models.status import Status
from openapi_client.models.statuses import Statuses
from openapi_client.models.webhook_status import WebhookStatus
from openapi_client.models.webhook_url import WebhookUrl
